### ISSUE TITLE
compile SpaceTx benchmarking results

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1306]
As a working group 5 member, I want to see processed spaceTX benchmarking results from smFISH and ISS in an organized aws folder, so that I can start my benchmarking analysis.

- [ ] format ISS mouse dataset into SpaceTX

- [ ] format smFISH dataset into SpaceTX

- [ ] write a workflow processing file for ISS

- [ ] write a workflow processing file for smFISH

- [ ] process full ISS dataset with starfish 

- [ ] process full smFISH dataset with starfish 

- [ ] merge results from processed ISS dataset and put in organized aws bucket 

- [ ]  merge results from processed smFISH dataset and put in organized aws bucket
