### ISSUE TITLE
Implement SpotFinding Refactor

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1514]
This epic will track the work proposed in #1500 

- [x] Create DecodedIntensityTable  -  #1489
- [x] Create new modules and data structure - #1515
- [x] Set up physical coordinates - #1516
- [x] Set up logging to work with new modules - #1517
- [x] Refactor ISS spot finding - #1518
- [x] Refactor osmFISH spotFinding - #1594 
- [x] Refactor StarMap spotFinding - #1577
- [x] Refactor smFISH spotFinding - #1580 
- [ ] Integrate Graph based decoding #1482 into new modules - #1613
- [ ] Formalize the ability for spot detection to return extra data - #1615
